version: '3'

env:
  TASK_TEMP_DIR: /home/dnk/.task

tasks:
  default:
    desc: Pull and build run
    cmds:
      - git pull
      - task: build

  build:
    desc: Build run binary
    sources:
      - ./*.go
      - go.mod
      - go.sum
    generates:
      - /home/dnk/bin/run
    cmds:
      - go build -o ~/bin/run .

  clean:
    desc: Remove run binary
    cmds:
      - rm -f ~/bin/run
